name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # ──────────────────────────────────────────
  server:
    name: Server Tests & Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js (Server)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Server Dependencies
        run: npm ci

      - name: Run ESLint (Server)
        run: npm run lint

      - name: Run Server Tests
        run: npm test       # <-- burada auth + scan integration test’leriniz koşuyor

  # ──────────────────────────────────────────
  client:
    name: Client Lint & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js (Client)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Client Dependencies
        run: npm ci

      - name: Run ESLint (Client)
        run: npm run lint

      - name: Build Client
        run: npm run build
